spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cw1mo4ku2tur.us-east-1.rds.amazonaws.com/employeedb?createDatabaseIfNotExist=true&autoReconnect=true&showSSL=false
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5000